#!/usr/bin/env python3
"""
Reset Project Script for AutoGen TS Engine

This script resets an existing project to start fresh with new scrum sprints.
"""

import os
import sys
import shutil
from pathlib import Path


def main():
    """Reset a project to start fresh."""
    
    print("🔄 AutoGen TS Engine - Reset Project")
    print("=" * 50)
    
    # Get project path
    if len(sys.argv) > 1:
        project_path = Path(sys.argv[1])
    else:
        project_path = Path.cwd()
    
    if not project_path.exists():
        print(f"❌ Project path does not exist: {project_path}")
        sys.exit(1)
    
    print(f"📁 Resetting project: {project_path}")
    
    # Directories to reset/remove
    reset_dirs = [
        "scrum",
        "src", 
        "tests",
        "project_db",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        ".cache"
    ]
    
    # Files to remove (generated by engine)
    reset_files = [
        "requirements.txt",
        "setup.py", 
        "pyproject.toml",
        "README.md"
    ]
    
    print("\n🗑️ Removing generated directories...")
    for dir_name in reset_dirs:
        dir_path = project_path / dir_name
        if dir_path.exists():
            try:
                shutil.rmtree(dir_path)
                print(f"   ✅ Removed: {dir_name}/")
            except Exception as e:
                print(f"   ❌ Failed to remove {dir_name}/: {e}")
    
    print("\n🗑️ Removing generated files...")
    for file_name in reset_files:
        file_path = project_path / file_name
        if file_path.exists():
            try:
                os.remove(file_path)
                print(f"   ✅ Removed: {file_name}")
            except Exception as e:
                print(f"   ❌ Failed to remove {file_name}: {e}")
    
    print("\n✅ Project reset completed!")
    print(f"\n📁 Project structure after reset:")
    print(f"   {project_path}/")
    print(f"   ├── config/ (preserved)")
    print(f"   │   ├── settings.md")
    print(f"   │   ├── agents.md")
    print(f"   │   └── ...")
    print(f"   └── (all generated files removed)")
    
    print(f"\n🚀 To start fresh scrum process:")
    print(f"1. Navigate to project directory:")
    print(f"   cd {project_path}")
    print(f"")
    print(f"2. Run the engine to start new sprints:")
    print(f"   python /path/to/autogen-ts-engine/test_mock_engine.py")
    print(f"")
    print(f"💡 The engine will:")
    print(f"   - Create new scrum/ directory")
    print(f"   - Start fresh sprint 1")
    print(f"   - Generate new project files")
    print(f"   - Initialize new vector database")


if __name__ == "__main__":
    main()
